import { Inter } from 'next/font/google'
import './globals.css'
import { Layout, Space } from 'antd'
import { Content, Footer, Header } from 'antd/es/layout/layout'
import StyledComponentsRegistry from '@/lib/AntedRegistry'
import MenuHandler from './Menu'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  //style
  const headerStyle={
    height: 64,
    paddingInline: 50,
    display: 'flex',
    lineHeight: '64px',
    color:'#fff',
    backgroundColor: '#26201A'
  };

  const contentStyle={
    minHeight: 780,
    lineHeight: '120px',
  };
  const footerStyle ={
    textAlign: 'center',
    color: '#26201A',
  }

  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <div>
          <StyledComponentsRegistry>
            <Space direction="vertical" style={{ width: '100%' }} size={[0, 48]}>
              <Layout>
                <Header style={headerStyle}>
                  <MenuHandler></MenuHandler>
                </Header>
                <Content style={contentStyle}>
                  {children}
                </Content>
                <Footer style={footerStyle}> 
                  SKBOARD ©2023 Created by SEULKI
                </Footer>
              </Layout>
            </Space>
          </StyledComponentsRegistry>
        </div>
      </body>
    </html>
  )
}
